//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskHive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskHive.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the folder was cancelled.
        /// </summary>
        public static string Accesscancelled {
            get {
                return ResourceManager.GetString("Accesscancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB is already installed.
        /// </summary>
        public static string ADBIsInstalled {
            get {
                return ResourceManager.GetString("ADBIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB is not installed on this system.
        ///Please install Android SDK Platform Tools..
        /// </summary>
        public static string ADBisnotinstalled {
            get {
                return ResourceManager.GetString("ADBisnotinstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add via Excel.
        /// </summary>
        public static string addexcel {
            get {
                return ResourceManager.GetString("addexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create single or multiple users (via Excel file).
        /// </summary>
        public static string addsingleclient {
            get {
                return ResourceManager.GetString("addsingleclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Management.
        /// </summary>
        public static string ApplicantManagement {
            get {
                return ResourceManager.GetString("ApplicantManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application phone number.
        /// </summary>
        public static string AppNumber {
            get {
                return ResourceManager.GetString("AppNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number that will be used to connect this application to your mobile phone. This number is required for communication through WhatsApp and Telegram. Make sure the number is active and includes the country code .
        /// </summary>
        public static string AppNumDescription {
            get {
                return ResourceManager.GetString("AppNumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string areyousureyouwanttodelete {
            get {
                return ResourceManager.GetString("areyousureyouwanttodelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance Service Type.
        /// </summary>
        public static string AssistanceServiceType {
            get {
                return ResourceManager.GetString("AssistanceServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created successfully.
        /// </summary>
        public static string backucreatedsuccess {
            get {
                return ResourceManager.GetString("backucreatedsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup creates a copy of your database and saves it to a location you choose.
        ///This copy can be used to restore your data if the original database is lost, damaged, or accidentally deleted.
        ///It is recommended to create backups regularly to keep your data safe.
        /// </summary>
        public static string backupdes {
            get {
                return ResourceManager.GetString("backupdes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call And Message Form.
        /// </summary>
        public static string CallMessageForm {
            get {
                return ResourceManager.GetString("CallMessageForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete an active user. To delete a user, you must first deactivate them and then proceed with deletion.
        /// </summary>
        public static string checkuseractive {
            get {
                return ResourceManager.GetString("checkuseractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Information.
        /// </summary>
        public static string ClientInfo {
            get {
                return ResourceManager.GetString("ClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the office address as it should appear in Google Maps.
        ///This address is used to calculate routes and directions from the office location to the selected destination for personnel.
        ///Please enter a complete and accurate address to ensure correct navigation..
        /// </summary>
        public static string companyaddDes {
            get {
                return ResourceManager.GetString("companyaddDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section, you can register and manage information about companies and service providers.
        ///This information includes contact details, addresses, and communication methods, and is used for tracking and contacting these organizations..
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string companyname {
            get {
                return ResourceManager.GetString("companyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Note.
        /// </summary>
        public static string CompanyNote {
            get {
                return ResourceManager.GetString("CompanyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Phone.
        /// </summary>
        public static string companyphone {
            get {
                return ResourceManager.GetString("companyphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Selection.
        /// </summary>
        public static string CompanySelection {
            get {
                return ResourceManager.GetString("CompanySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to set whether the company is active or inactive.
        /// </summary>
        public static string companystatuscheckbox {
            get {
                return ResourceManager.GetString("companystatuscheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Website.
        /// </summary>
        public static string companywebsite {
            get {
                return ResourceManager.GetString("companywebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connect.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy number.
        /// </summary>
        public static string copynumber {
            get {
                return ResourceManager.GetString("copynumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string customeraddress {
            get {
                return ResourceManager.GetString("customeraddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Description.
        /// </summary>
        public static string CustomerDescription {
            get {
                return ResourceManager.GetString("CustomerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section, you can add, edit, delete, and print customer information.
        ///You can also manage and search customer records.
        /// </summary>
        public static string Customerwinforminfo {
            get {
                return ResourceManager.GetString("Customerwinforminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the search type from the list, enter the desired value in the field, and click the Search button.
        ///Results will be displayed based on the beginning of the entered text (prefix)..
        /// </summary>
        public static string dessearchcompleted {
            get {
                return ResourceManager.GetString("dessearchcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Connected.
        /// </summary>
        public static string DeviceConnected {
            get {
                return ResourceManager.GetString("DeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was established.
        /// </summary>
        public static string deviceconneted {
            get {
                return ResourceManager.GetString("deviceconneted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form allows you to manage your Android device using ADB commands.
        ///You can start or restart the ADB server, connect to your device, and perform actions such as installing apps, transferring files, or viewing logs..
        /// </summary>
        public static string devicedes {
            get {
                return ResourceManager.GetString("devicedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed successfully.
        /// </summary>
        public static string DeviceExecuted_successfully {
            get {
                return ResourceManager.GetString("DeviceExecuted successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your device is not connected, please click the ‘Run’ button to start the ADB server and establish the connection..
        /// </summary>
        public static string deviceisnotconnect {
            get {
                return ResourceManager.GetString("deviceisnotconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Number.
        /// </summary>
        public static string DeviceNumber {
            get {
                return ResourceManager.GetString("DeviceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education / Language Services.
        /// </summary>
        public static string EducationLanguageServices {
            get {
                return ResourceManager.GetString("EducationLanguageServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Email.
        /// </summary>
        public static string EmailCompany {
            get {
                return ResourceManager.GetString("EmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 16-digit password generated by the company email account.
        /// </summary>
        public static string EmailCompanycodegen {
            get {
                return ResourceManager.GetString("EmailCompanycodegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the company email address that will be used to access the mailbox through the application.
        ///This email allows the application to connect to the email inbox and manage messages from within the program.
        ///Make sure the email address is valid and active.
        /// </summary>
        public static string EmailDes {
            get {
                return ResourceManager.GetString("EmailDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency / Crisis Services.
        /// </summary>
        public static string EmergencyCrisis_Services {
            get {
                return ResourceManager.GetString("EmergencyCrisis Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment / Vocational Services.
        /// </summary>
        public static string EmploymentVocationalServices {
            get {
                return ResourceManager.GetString("EmploymentVocationalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify User Status.
        /// </summary>
        public static string EnableDes {
            get {
                return ResourceManager.GetString("EnableDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable service status.
        /// </summary>
        public static string Enabledisableservicestatus {
            get {
                return ResourceManager.GetString("Enabledisableservicestatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a message to send.
        /// </summary>
        public static string Entemessagesend {
            get {
                return ResourceManager.GetString("Entemessagesend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number you want to call.You can type the number or copy and paste it here.
        /// </summary>
        public static string Enterthephonenumberyouwant {
            get {
                return ResourceManager.GetString("Enterthephonenumberyouwant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one user exists in the list. You are not allowed to delete it.
        /// </summary>
        public static string ErroDeleteUser {
            get {
                return ResourceManager.GetString("ErroDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new user, you must first select and verify the Device Number of an existing user.
        ///Only users with a valid registered device are allowed to add new users..
        /// </summary>
        public static string ErrorAddUser {
            get {
                return ResourceManager.GetString("ErrorAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number is already registered.
        /// </summary>
        public static string ErrorClientIdRegistered {
            get {
                return ResourceManager.GetString("ErrorClientIdRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establish connection with the device.
        /// </summary>
        public static string Establishconnectiondevice {
            get {
                return ResourceManager.GetString("Establishconnectiondevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Excel file is empty.
        /// </summary>
        public static string excelfileempty {
            get {
                return ResourceManager.GetString("excelfileempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel folder not found.
        /// </summary>
        public static string Excelfoldernotfound {
            get {
                return ResourceManager.GetString("Excelfoldernotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExporttoExcel {
            get {
                return ResourceManager.GetString("ExporttoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer.
        /// </summary>
        public static string File_Transfer {
            get {
                return ResourceManager.GetString("File-Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Attached.
        /// </summary>
        public static string FileAttached {
            get {
                return ResourceManager.GetString("FileAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copied successfully.
        /// </summary>
        public static string Filecopiedsuccessfully {
            get {
                return ResourceManager.GetString("Filecopiedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large!.
        /// </summary>
        public static string Filelarge {
            get {
                return ResourceManager.GetString("Filelarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your Service User ID by:.
        /// </summary>
        public static string FindUserID {
            get {
                return ResourceManager.GetString("FindUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string fname {
            get {
                return ResourceManager.GetString("fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you forgot your password, enter your email and a reset link will be sent to you.
        /// </summary>
        public static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map.
        /// </summary>
        public static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High above the peaks.
        /// </summary>
        public static string goul {
            get {
                return ResourceManager.GetString("goul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health / Medical Services.
        /// </summary>
        public static string HealthMedicalServices {
            get {
                return ResourceManager.GetString("HealthMedicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing / Shelter Services.
        /// </summary>
        public static string HousingShelterServices {
            get {
                return ResourceManager.GetString("HousingShelterServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I got it.
        /// </summary>
        public static string Igotit {
            get {
                return ResourceManager.GetString("Igotit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import template file.
        /// </summary>
        public static string Importexcelfile {
            get {
                return ResourceManager.GetString("Importexcelfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clients imported successfully.
        /// </summary>
        public static string imprtsuccess {
            get {
                return ResourceManager.GetString("imprtsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive clients.
        /// </summary>
        public static string inactiveclient {
            get {
                return ResourceManager.GetString("inactiveclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive users.
        /// </summary>
        public static string Inactiveusers {
            get {
                return ResourceManager.GetString("Inactiveusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android SDK Platform Tools is required to connect your device. Click Install to download and install it..
        /// </summary>
        public static string InstallSKK {
            get {
                return ResourceManager.GetString("InstallSKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet is connected.
        /// </summary>
        public static string Internetconnected {
            get {
                return ResourceManager.GetString("Internetconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet is disconnected.
        /// </summary>
        public static string Internetdisconnected {
            get {
                return ResourceManager.GetString("Internetdisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items have been successfully registered.
        /// </summary>
        public static string itemsSuccessfully {
            get {
                return ResourceManager.GetString("itemsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal / Immigration Services.
        /// </summary>
        public static string LegalImmigrationServices {
            get {
                return ResourceManager.GetString("LegalImmigrationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client list is empty.
        /// </summary>
        public static string listclientempty {
            get {
                return ResourceManager.GetString("listclientempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a template.
        /// </summary>
        public static string maketamplate {
            get {
                return ResourceManager.GetString("maketamplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Company.
        /// </summary>
        public static string ManageCompany {
            get {
                return ResourceManager.GetString("ManageCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        public static string ManageUser {
            get {
                return ResourceManager.GetString("ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Completed.
        /// </summary>
        public static string MarkCompleted {
            get {
                return ResourceManager.GetString("MarkCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item to delete.
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is connected to the PC, but the application cannot communicate with it. .
        /// </summary>
        public static string MessageDevicdconnectedbutNoconnection {
            get {
                return ResourceManager.GetString("MessageDevicdconnectedbutNoconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the backup file path to restore.
        /// </summary>
        public static string MessageFileRestore {
            get {
                return ResourceManager.GetString("MessageFileRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file path for the backup file.
        /// </summary>
        public static string MessageSelectPath {
            get {
                return ResourceManager.GetString("MessageSelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sending failed.
        /// </summary>
        public static string Messagesendingfailed {
            get {
                return ResourceManager.GetString("Messagesendingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent successfully.
        /// </summary>
        public static string Messagesentsuccessfully {
            get {
                return ResourceManager.GetString("Messagesentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected item?.
        /// </summary>
        public static string MsgDelete {
            get {
                return ResourceManager.GetString("MsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user?.
        /// </summary>
        public static string MsgDelUser {
            get {
                return ResourceManager.GetString("MsgDelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email was sent successfully. Please check your email.
        /// </summary>
        public static string msgsentemail {
            get {
                return ResourceManager.GetString("msgsentemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Website.
        /// </summary>
        public static string MyWebsite {
            get {
                return ResourceManager.GetString("MyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string navigate {
            get {
                return ResourceManager.GetString("navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter the address manually or select the desired address using one of the available buttons..
        /// </summary>
        public static string NavigateDes {
            get {
                return ResourceManager.GetString("NavigateDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new message.
        /// </summary>
        public static string newmessage {
            get {
                return ResourceManager.GetString("newmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new SMS message.
        /// </summary>
        public static string NewSMSmessage {
            get {
                return ResourceManager.GetString("NewSMSmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to edit the existing template (Yes) or create a new template (No)?
        ///.
        /// </summary>
        public static string newtemplateoredit {
            get {
                return ResourceManager.GetString("newtemplateoredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address specified.
        /// </summary>
        public static string NoAddressspecified {
            get {
                return ResourceManager.GetString("NoAddressspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form remains open after saving.
        /// </summary>
        public static string nocloseaftersave {
            get {
                return ResourceManager.GetString("nocloseaftersave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device connected.
        /// </summary>
        public static string Nodeviceconnected {
            get {
                return ResourceManager.GetString("Nodeviceconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel is not installed on this computer or no program is associated with .xlsx files..
        /// </summary>
        public static string Noexcelinstall {
            get {
                return ResourceManager.GetString("Noexcelinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Image.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected.
        /// </summary>
        public static string Noitemselected {
            get {
                return ResourceManager.GetString("Noitemselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No number entered.
        /// </summary>
        public static string Nonumberentered {
            get {
                return ResourceManager.GetString("Nonumberentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter numbers only.
        /// </summary>
        public static string notclientid {
            get {
                return ResourceManager.GetString("notclientid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add multiple phone numbers separated by a comma (,), for example:
        ///466891245,466151512,...
        ///Maximum of 4 numbers.
        /// </summary>
        public static string notclientphone {
            get {
                return ResourceManager.GetString("notclientphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientTemplate.xlsx not found in Excel folder.
        /// </summary>
        public static string notfoundinExcelfolder {
            get {
                return ResourceManager.GetString("notfoundinExcelfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your gender.
        /// </summary>
        public static string notgender {
            get {
                return ResourceManager.GetString("notgender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Telegram ID without @.
        /// </summary>
        public static string notidtelegram {
            get {
                return ResourceManager.GetString("notidtelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting this option, the user will appear as active in the list.
        /// </summary>
        public static string notsit {
            get {
                return ResourceManager.GetString("notsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365.
        /// </summary>
        public static string office365 {
            get {
                return ResourceManager.GetString("office365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Address.
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form is used to configure the office settings.
        ///Here you can enter and manage information about the office, such as the office name, address, email, and phone number.
        ///Please ensure that all information is accurate and up to date.
        /// </summary>
        public static string officedes {
            get {
                return ResourceManager.GetString("officedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Name.
        /// </summary>
        public static string OfficeName {
            get {
                return ResourceManager.GetString("OfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string Ongoing {
            get {
                return ResourceManager.GetString("Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the action you want.
        /// </summary>
        public static string OptionClient {
            get {
                return ResourceManager.GetString("OptionClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other / Extra Crisis Services.
        /// </summary>
        public static string OtherExtraCrisisServices {
            get {
                return ResourceManager.GetString("OtherExtraCrisisServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        public static string Personnel {
            get {
                return ResourceManager.GetString("Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type the  Service User ID.
        /// </summary>
        public static string Pleasetypethe_ServiceUserID {
            get {
                return ResourceManager.GetString("Pleasetypethe ServiceUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer not to say.
        /// </summary>
        public static string Prefernottosay {
            get {
                return ResourceManager.GetString("Prefernottosay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        public static string printpreview {
            get {
                return ResourceManager.GetString("printpreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read / Unread.
        /// </summary>
        public static string ReadUnread {
            get {
                return ResourceManager.GetString("ReadUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form to set a reminder for your important tasks or events. Choose the date and time so you won’t forget them..
        /// </summary>
        public static string ReminderAdddes {
            get {
                return ResourceManager.GetString("ReminderAdddes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Date and Time.
        /// </summary>
        public static string ReminderDateTime {
            get {
                return ResourceManager.GetString("ReminderDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form to set a reminder. You can choose the date and time, so you won’t forget your important tasks or events..
        /// </summary>
        public static string ReminderWinDes {
            get {
                return ResourceManager.GetString("ReminderWinDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore allows you to recover your database from a previously created backup file.
        ///When you restore a backup, the current database will be replaced with the data from the backup file.
        ///Make sure to select the correct backup file before restoring.
        /// </summary>
        public static string Restoreded {
            get {
                return ResourceManager.GetString("Restoreded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database restored successfully.
        /// </summary>
        public static string Restoredsuccessfully {
            get {
                return ResourceManager.GetString("Restoredsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string Savedsuccessfully {
            get {
                return ResourceManager.GetString("Savedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search customer by.
        /// </summary>
        public static string Searchcustomerby {
            get {
                return ResourceManager.GetString("Searchcustomerby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityStamp.
        /// </summary>
        public static string SecurityStamp {
            get {
                return ResourceManager.GetString("SecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string selectall {
            get {
                return ResourceManager.GetString("selectall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option from the list below to continue.
        /// </summary>
        public static string Selectanoptionfromthelistbelow {
            get {
                return ResourceManager.GetString("Selectanoptionfromthelistbelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer to register the job.
        /// </summary>
        public static string selectcustomerregisterjob {
            get {
                return ResourceManager.GetString("selectcustomerregisterjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the contracting party for the new request.
        /// </summary>
        public static string selectrequest {
            get {
                return ResourceManager.GetString("selectrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option from the list.
        /// </summary>
        public static string selectuser {
            get {
                return ResourceManager.GetString("selectuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string sendemail {
            get {
                return ResourceManager.GetString("sendemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string Sendmessage {
            get {
                return ResourceManager.GetString("Sendmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send messages to customers through this form.
        /// </summary>
        public static string sendmessagetouserinternet {
            get {
                return ResourceManager.GetString("sendmessagetouserinternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message to the user.
        /// </summary>
        public static string Sendmessageuser {
            get {
                return ResourceManager.GetString("Sendmessageuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message to User Panel.
        /// </summary>
        public static string SendMessageUserPanel {
            get {
                return ResourceManager.GetString("SendMessageUserPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Status.
        /// </summary>
        public static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service User.
        /// </summary>
        public static string ServiceUser {
            get {
                return ResourceManager.GetString("ServiceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service User ID.
        /// </summary>
        public static string ServiceUserID {
            get {
                return ResourceManager.GetString("ServiceUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Worker.
        /// </summary>
        public static string ServiceWorker {
            get {
                return ResourceManager.GetString("ServiceWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Folder Name.
        /// </summary>
        public static string ShareFoldeName {
            get {
                return ResourceManager.GetString("ShareFoldeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Profile.
        /// </summary>
        public static string showprofile {
            get {
                return ResourceManager.GetString("showprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situation.
        /// </summary>
        public static string situation {
            get {
                return ResourceManager.GetString("situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social / Cultural Integration Services.
        /// </summary>
        public static string SocialCulturalIntegrationServices {
            get {
                return ResourceManager.GetString("SocialCulturalIntegrationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date – End date.
        /// </summary>
        public static string StartdateEnddate {
            get {
                return ResourceManager.GetString("StartdateEnddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Management.
        /// </summary>
        public static string Task_Management {
            get {
                return ResourceManager.GetString("Task-Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the task is completed, change the status from Ongoing to Completed.
        /// </summary>
        public static string taskcompeleted {
            get {
                return ResourceManager.GetString("taskcompeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskJobs.
        /// </summary>
        public static string TaskJobs {
            get {
                return ResourceManager.GetString("TaskJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task List.
        /// </summary>
        public static string tasklist {
            get {
                return ResourceManager.GetString("tasklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Telegram username or phone number associated with the company account.
        ///This information is used to connect the application to the company’s Telegram account and manage messages through the program.
        ///Make sure the account is active and accessible..
        /// </summary>
        public static string TelegramDes {
            get {
                return ResourceManager.GetString("TelegramDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram ID.
        /// </summary>
        public static string TelegramID {
            get {
                return ResourceManager.GetString("TelegramID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customers.
        /// </summary>
        public static string totalclients {
            get {
                return ResourceManager.GetString("totalclients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of companies.
        /// </summary>
        public static string totalcompanies {
            get {
                return ResourceManager.GetString("totalcompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the network folder. Error.
        /// </summary>
        public static string UnableConnecttonetwork {
            get {
                return ResourceManager.GetString("UnableConnecttonetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Mode.
        /// </summary>
        public static string User_Login_Mode {
            get {
                return ResourceManager.GetString("User Login Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with ID  is already registered.
        /// </summary>
        public static string UserIDRegistered {
            get {
                return ResourceManager.GetString("UserIDRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user information.
        /// </summary>
        public static string userinfo {
            get {
                return ResourceManager.GetString("userinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email does not match the specified user.
        /// </summary>
        public static string userisnotmatchwithemail {
            get {
                return ResourceManager.GetString("userisnotmatchwithemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is inactive.
        /// </summary>
        public static string userlogininactive {
            get {
                return ResourceManager.GetString("userlogininactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string userloginnotfound {
            get {
                return ResourceManager.GetString("userloginnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user was found with the provided information. Please check your username.
        /// </summary>
        public static string usernotfound {
            get {
                return ResourceManager.GetString("usernotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect.
        /// </summary>
        public static string userwrong {
            get {
                return ResourceManager.GetString("userwrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Notifications.
        /// </summary>
        public static string ViewNotifications {
            get {
                return ResourceManager.GetString("ViewNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather conditions.
        /// </summary>
        public static string Weather_conditions {
            get {
                return ResourceManager.GetString("Weather conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather link.
        /// </summary>
        public static string WeatherLink {
            get {
                return ResourceManager.GetString("WeatherLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Status.
        /// </summary>
        public static string WeatherStatus {
            get {
                return ResourceManager.GetString("WeatherStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web application.
        /// </summary>
        public static string webapplication {
            get {
                return ResourceManager.GetString("webapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form is used for user management.
        ///Here you can create new users, edit or delete user information, and enable or disable accounts..
        /// </summary>
        public static string WinUserDes {
            get {
                return ResourceManager.GetString("WinUserDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password is incorrect.
        /// </summary>
        public static string wronguserandpass {
            get {
                return ResourceManager.GetString("wronguserandpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string Youhave {
            get {
                return ResourceManager.GetString("Youhave", resourceCulture);
            }
        }
    }
}
